export { default as LoginPage } from "./auth/LoginPage.jsx";
export { default as RegisterPage } from "./auth/RegisterPage.jsx";
export { default as AllBrandsPage } from "./brands/AllBrandsPage.jsx";
export { default as CartPage } from "./cart/CartPage.jsx";
export { default as AllCategoriesPage } from "./categories/AllCategoriesPage.jsx";
export { default as PaymentMethodPage } from "./checkOut/PaymentMethodPage.jsx";
export { default as Home } from "./home/HomePage.jsx";
export { default as ProductsDetailesPage } from "./products/ProductsDetailesPage.jsx";
export { default as ShopProductPage } from "./products/ShopProductPage.jsx";
